import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import './globals.css'
import Content from '../main-page/page'
import { Header } from '@/Header/page'
import Footer from '@/Footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'News updates',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
